### ISSUE TITLE
Incompatible with beta.49+

### ISSUE THREAD

**Issue by genox** [r1tsuu/payload-enchants#78]
Hi there,

The breaking changes in beta.49 regarding imports (https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.49) probably affect all of the plugins. :/

**Comment by r1tsuu** [comment]
It could be, but i personally wouldn't use 48+ beta at the moment

**Comment by HarleySalas** [comment]
would you accept a PR that aligns the imports with the current version now? (`3.0.0-beta.56`)

**Comment by r1tsuu** [comment]
> would you accept a PR that aligns the imports with the current version now? (`3.0.0-beta.56`)

ive already done that https://github.com/r1tsuu/payload-enchants/tree/payload-53

you can install [1.2.0-pre.0](https://www.npmjs.com/package/@payload-enchants/cached-local-api/v/1.2.0-pre.0)
just translator doesn't work because of one Payload issue (it's resolved on their side, so i need to update it)

**Comment by r1tsuu** [comment]
Completed in https://github.com/r1tsuu/payload-enchants/pull/82
